import { createSlice } from "@reduxjs/toolkit";

 

const ProductSlice =createSlice ({
  name :"products",
  initialState : [{
    id:1,
    name:"Huile de citron" , 
    // descirption:"  L'huile essentielle de citron est extraite des zestes frais du citron, Citrus limon, qui appartient à la famille botanique des Rutacées. Cette huile essentielle est obtenue par un processus de pression à froid des zestes de citron, ce qui permet de capturer les composés volatils et aromatiques présents dans la peau de ce fruit. Composition Chimique : L'huile essentielle de citron est composée principalement de monoterpènes et de sesquiterpènes, qui sont des hydrocarbures volatils. Les principaux constituants de l'huile essentielle de citron comprennent le limonène (environ 65 à 75 %), le béta-pinène, le gamma-terpinène, l'alpha-pinène et le sabinène, entre autres.Propriétés Biologiques et Applications :Antioxydant : Le limonène, un composé majeur de l'huile essentielle de citron, est un puissant antioxydant. Il peut aider à neutraliser les radicaux libres dans le corps, contribuant ainsi à la protection contre les dommages cellulaires et le vieillissement prématuré. Antibactérien et Antifongique : L'huile essentielle de citron possède des propriétés antibactériennes et antifongiques. Elle peut être utilisée comme agent de nettoyage naturel pour désinfecter les surfaces et aider à éliminer les bactéries et les champignons. Stimulant : L'arôme vif et revigorant de l'huile essentielle de citron a des propriétés stimulantes qui peuvent aider à améliorer l'humeur, à réduire le stress et à favoriser la concentration. Support Digestif : L'huile essentielle de citron est parfois utilisée pour favoriser la digestion en stimulant la sécrétion d'enzymes digestives et en facilitant le mouvement intestinal. Soin de la Peau : En raison de ses propriétés antioxydantes et de sa capacité à tonifier la peau, l'huile essentielle de citron est parfois ajoutée à des produits de soins de la peau pour aider à rafraîchir et à éclaircir le teint.",
    image : 'images/huile de citron.png',
    price: 100},
  
    {
    id:2,
    name:"huile végétale de lentisque pistachier" , 
    descirption:"L'huile essentielle de lentisque pistachier est extraite de la résine du lentisque pistachier (Pistacia lentiscus), un petit arbuste appartenant à la famille des Anacardiacées. Cette huile essentielle est appréciée pour son arôme unique et ses propriétés bénéfiques pour la santé et le bien-être. Voici une description scientifique de l'huile essentielle de lentisque pistachier : Composition Chimique : L'huile essentielle de lentisque pistachier est composée d'une variété de composés chimiques, notamment des monoterpenes, des sesquiterpenes et des esters. Les constituants chimiques spécifiques varient en fonction de la source géographique et des conditions de récolte, mais les principaux comprennent .Alpha-pinène : Un monoterpène présent en quantités variables dans l'huile de lentisque pistachier, ayant des propriétés anti-inflammatoires et antioxydantes. Limonène : Un monoterpène qui peut aider à soutenir le système immunitaire et favoriser la santé générale. Beta-caryophyllène : Un sesquiterpène aux propriétés anti-inflammatoires et analgésiques. Alpha-phellandrène : Un monoterpène qui peut avoir des effets relaxants et apaisants. Acétate de bornyle : Un ester qui ajoute des notes douces à l'arôme et peut avoir des propriétés calmantes. Propriétés et Utilisations :Soutien Respiratoire : L'huile essentielle de lentisque pistachier peut aider à apaiser les voies respiratoires en cas de congestion nasale et de toux. Soutien Digestif : Certains composés de l'huile de lentisque pistachier peuvent soutenir la digestion en favorisant la production d'enzymes digestives et en soulageant les inconforts gastro-intestinaux. Soin de la Peau : L'huile essentielle de lentisque pistachier peut être utilisée pour favoriser la santé de la peau, apaiser les irritations cutanées et soutenir la régénération cellulaire. Effet Calmant : L'arôme unique de l'huile de lentisque pistachier peut avoir des effets relaxants sur l'esprit et aider à réduire le stress et l'anxiété. Antioxydant : Certains composés de l'huile peuvent avoir des propriétés antioxydantes qui aident à protéger les cellules contre les dommages oxydatifs. ",
    image:"images/lentistiqe pistachier.png",
    price:650
  
  },
  {
    id:3,
    name:"huile d'orange" , 
    descirption:"L'huile essentielle d'orange est extraite des zestes d'agrumes du fruit Citrus sinensis, appartenant à la famille des Rutacées. Cette huile essentielle est largement utilisée pour son arôme rafraîchissant et fruité, ainsi que pour ses nombreuses propriétés bénéfiques pour la santé et le bien-être. Voici une description scientifique de l'huile essentielle d'orange : Composition Chimique : L'huile essentielle d'orange est composée d'une variété de composés chimiques, principalement des monoterpènes et des sesquiterpènes. Les constituants chimiques spécifiques varient en fonction de la variété d'orange, mais les principaux comprennent : Limonène : Le limonène est le composant majeur de l'huile essentielle d'orange, représentant généralement plus de 90 % de sa composition. Il confère à l'huile son arôme caractéristique et possède des propriétés antioxydantes, anti-inflammatoires et digestives. Myrcène : Un monoterpène présent en quantités variables dans l'huile d'orange, ayant des propriétés anti-inflammatoires et relaxantes. Alpha-pinène, Béta-pinène : Des monoterpènes qui contribuent à l'arôme et peuvent avoir des effets antimicrobiens et anti-inflammatoires. Sabinène : Un monoterpène présent dans certaines variétés d'orange, qui peut avoir des propriétés antioxydantes et anti-inflammatoire .Propriétés et Utilisations : Effet Revigorant : L'arôme frais et fruité de l'huile essentielle d'orange est connu pour stimuler l'énergie et améliorer l'humeur. Son parfum joyeux peut aider à éloigner le stress et favoriser la relaxation. Antioxydant : Le limonène dans l'huile d'orange a des propriétés antioxydantes qui peuvent aider à neutraliser les radicaux libres et protéger les cellules contre les dommages oxydatifs. Soutien Digestif : L'huile essentielle d'orange peut favoriser la digestion en stimulant la production d'enzymes digestives et en apaisant les inconforts gastro-intestinaux. Soin de la Peau : En raison de ses propriétés antibactériennes et anti-inflammatoires, l'huile d'orange est parfois utilisée dans les produits de soins de la peau pour traiter les imperfections cutanées et favoriser un teint éclatant. Aromathérapie : L'huile essentielle d'orange est largement utilisée en aromathérapie pour favoriser la relaxation, soulager l'anxiété et améliorer le bien-être émotionnel.",
    image:"images/huile d'orange.png",
    price:650
  
  },
  {
    id:4,
    name:"huile de lavandre" , 
    descirption:" L'huile essentielle de lavande, extraite des fleurs de Lavandula angustifolia, est largement étudiée pour ses propriétés chimiques et ses applications dans divers domaines, notamment l'aromathérapie, la médecine, la cosmétologie et la recherche scientifique. Voici une description scientifique de l'huile essentielle de lavande : Composition Chimique : L'huile essentielle de lavande se compose d'une combinaison complexe de composés chimiques naturels qui confèrent à l'huile ses propriétés aromatiques et thérapeutiques. Les principaux constituants chimiques de l'huile essentielle de lavande comprennent :  Linalol : Un monoterpène alcool présent en grande quantité dans l'huile de lavande. Il confère à l'huile son arôme caractéristique et a des propriétés apaisantes et relaxantes. Acétate de Linalyle : Un ester qui contribue à l'arôme doux et floral de l'huile de lavande. Il est également associé à ses propriétés relaxantes et calmantes. Cinéole (1,8-cinéole) : Un oxyde présent en quantités variables dans l'huile de lavande. Il peut avoir des effets positifs sur la santé respiratoire et contribuer à la clarté mentale. Camphre : Un terpène avec des propriétés rafraîchissantes et revigorantes, bien que présent en quantités plus faibles dans la lavande que dans d'autres variétés. Béta-caryophyllène : Un sesquiterpène présentant des propriétés anti-inflammatoires potentielles. Propriétés et Utilisations : Propriétés Anxiolytiques : L'huile essentielle de lavande a été étudiée pour ses effets anxiolytiques, contribuant à réduire l'anxiété et le stress. Elle peut influencer positivement les neurotransmetteurs cérébraux tels que la sérotonine. Effets sur le Système Nerveux : Des études suggèrent que l'huile de lavande peut influencer le système nerveux central en induisant une relaxation et en favorisant le sommeil. Anti-Inflammatoire et Antioxydant : Certains composés de l'huile essentielle de lavande ont démontré des propriétés anti-inflammatoires et antioxydantes potentielles. Antimicrobien : L'huile de lavande peut avoir des propriétés antimicrobiennes, notamment contre certaines bactéries et champignons pathogènes. Applications Topiques : En raison de ses propriétés apaisantes et cicatrisantes, l'huile de lavande est souvent utilisée dans les produits de soins de la peau pour favoriser la guérison des irritations cutanées mineures.",
    image:"images/huile de lavandre.png",
    price:650
  
  },
  {
    id:5,
    name:"huile de menthe" , 
    descirption:"L'huile essentielle de menthe, extraite des feuilles de diverses espèces de menthe, est réputée pour son arôme frais et mentholé ainsi que pour ses nombreuses applications en aromathérapie, en médecine et en soins personnels. Voici une description scientifique de l'huile essentielle de menthe : Composition Chimique : L'huile essentielle de menthe est composée d'une variété de composés chimiques, dont les principaux sont les monoterpènes et les cétones. Les constituants chimiques spécifiques varient en fonction de la variété de menthe, mais les principaux comprennent : Menthol : Le menthol est l'un des principaux composés de l'huile essentielle de menthe. Il confère à l'huile son arôme caractéristique de menthe poivrée et possède des propriétés rafraîchissantes et apaisantes. Menthone : Une cétone qui contribue également à l'arôme de menthe et peut avoir des propriétés stimulantes. Isomenthone, Menthofurane : D'autres cétones présentes en quantités variables dans l'huile de menthe. Alpha-pinène, Béta-pinène : Des monoterpènes qui contribuent à l'arôme et peuvent avoir des effets antiseptiques et anti-inflammatoires. Limonène : Un monoterpène présent dans certaines variétés de menthe, ayant des propriétés antioxydantes et bénéfiques pour la santé. Propriétés et Utilisations : Effets Digestifs : L'huile essentielle de menthe est réputée pour son potentiel à soulager les problèmes digestifs tels que les ballonnements, les gaz et les inconforts gastriques. Soutien Respiratoire : Le menthol dans l'huile de menthe peut aider à dégager les voies respiratoires, soulager la congestion nasale et favoriser la respiration libre. Soulagement Musculaire : Appliquée par voie topique, l'huile essentielle de menthe peut apporter un soulagement temporaire des douleurs musculaires et des tensions. Stimulation Mentale : L'arôme mentholé de la menthe peut aider à stimuler la concentration, la vigilance mentale et la clarté mentale. Soin Buccal : Le menthol est un ingrédient courant dans les produits de soins buccaux en raison de ses propriétés rafraîchissantes et antiseptiques. ",
    image:"images/huile de menthe.png",
    price:650
  
  },
  {
    id:6,
    name:"huile essenteil de Romarin" , 
    descirption:"L'huile essentielle de romarin est extraite des feuilles et des sommités fleuries du Rosmarinus officinalis, une plante aromatique appartenant à la famille des Lamiacées. Cette huile essentielle est appréciée pour son arôme puissant et frais ainsi que pour ses nombreuses applications en aromathérapie, en médecine naturelle et en soins de beauté. Voici une description scientifique de l'huile essentielle de romarin :Composition Chimique : L'huile essentielle de romarin est riche en composés chimiques naturels, notamment des monoterpènes, des cétones, des esters et des phénols. Les principaux constituants chimiques de l'huile de romarin comprennent :1,8-cinéole (Eucalyptol) : Un oxyde présent en quantités significatives dans l'huile de romarin, ayant des propriétés bénéfiques pour la santé respiratoire et des effets anti-inflammatoires. Camphre : Un monoterpène qui peut contribuer à la clarté mentale et à la stimulation. Alpha-pinène, Béta-pinène : Des monoterpènes aux propriétés antioxydantes et anti-inflammatoires. Véronal : Une cétone présente dans certaines variétés de romarin, avec des propriétés stimulantes et aromatiques. Acétate de bornyle : Un ester qui ajoute des notes douces et florales à l'arôme du romarin et peut avoir des effets calmants. Propriétés et Utilisations : Stimulation Mentale : L'huile essentielle de romarin est reconnue pour ses effets stimulants sur la clarté mentale, la concentration et la vigilance. Elle peut aider à éloigner la fatigue mentale et à améliorer la performance cognitive. Soutien Respiratoire : Le 1,8-cinéole dans l'huile de romarin peut aider à dégager les voies respiratoires, soulager la congestion et faciliter la respiration. Antioxydant et Anti-Inflammatoire : Certains composés de l'huile de romarin ont des propriétés antioxydantes qui peuvent aider à protéger les cellules contre les dommages oxydatifs. Elle peut également avoir des effets anti-inflammatoires. Soin Capillaire : L'huile essentielle de romarin est parfois utilisée dans les soins capillaires pour promouvoir la santé du cuir chevelu, réduire les pellicules et favoriser la croissance des cheveux. Relaxation Musculaire : Appliquée par voie topique, l'huile essentielle de romarin peut offrir un soulagement temporaire des tensions musculaires.",
    image:"images/huile essenteil de Romaarin.png",
    price:650
  
  }],
  reducers:{
    setProducts:(state,action)=>{
      return action.payload
    },
    filtreProduct:(state,action)=>{
      state=state.filter((el)=>el.name===action.payload)
      return state
    },
    findProduct:(state,action)=>{
      state = state.find((el)=>el.id===action.payload)
      return state
    }
  }
})

export const{setProducts,filtreProduct,findProduct} = ProductSlice.actions;
export default ProductSlice.reducer

